#!/bin/sh -e

if [ $# -lt 1 ]; then
    echo $0 '<query>'
    return 1
fi

IFS=:
for repo in /var/db/kiss/installed/ $KISS_PATH; do
    test -n "$repo" && find "$repo" -mindepth 1 -maxdepth 1 -iname '*'"$1"'*'
done
