#!/bin/sh -e

# Don't use extracted source to allow make reuse previous result
src=~/.cache/kiss/sources/linux/linux.git
cd "$src"

grep -q 'linux/stddef.h' ./tools/arch/x86/include/asm/insn.h || sed -i '/<asm\/byteorder.h>/i #include <linux/stddef.h>' ./tools/arch/x86/include/asm/insn.h
make mrproper

export KBUILD_OUTPUT="$HOME/.cache/kbuild"

mkdir -p "$KBUILD_OUTPUT"
mv "$OLDPWD/config" "$KBUILD_OUTPUT/.config"

make

mkdir -p "$1/boot"
make INSTALL_PATH="$1/boot" install
mv "$1/boot/vmlinuz" "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"
