#!/bin/sh -e
# Use the first kiss alternatives to fill in missing files

while [ $# -gt 0 ]; do
    case "$1" in
        -d|--dryrun)
            DRYRUN=1
            ;;
        *)
            echo $0 '[ -d | --dryrun ]'
            exit
            ;;
    esac
    shift
done

alts=$(kiss alternatives)

# Find list of files that are in `kiss alternatives` but not in the filesystem
results=$(echo "$alts" | while read -r pkg path; do
    if [ ! -e "$path" ]; then
        echo $pkg $path
    fi

# Use only the first package for the path
done | sort -u -k 2)

if [ -z "$results" ]; then
    echo "Nothing to do"
    exit
fi

echo "$results"

# Call kiss alternatives to update the paths
if [ -z "$DRYRUN" ]; then
    echo "$results" | kiss alternatives -
fi
