#!/bin/sh -e

echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-cscope \
    --enable-multibyte \
    --with-ex-name=ex \
    --with-view-name=vim-view \
    --enable-perlinterp=dynamic \
    --enable-pythoninterp=dynamic \
    --enable-python3interp=dynamic \
    --with-python3-config-dir=$(python3-config --configdir) \
    --enable-rubyinterp=dynamic \
    --enable-luainterp=dynamic \
    --enable-tclinterp=dynamic \
    --disable-netbeans \
    --disable-gpm \
    --disable-hangulinput \
    --disable-gui \
    --disable-nls \
    --with-x

make
make DESTDIR="$1" install
